// Copyright (c) 2019, NXP Semiconductors
[[settings]]
:numbered:

// #############################################################################
// #############################################################################
// #############################################################################

== Setting Up the Environment

This document explains the basic steps to start with _embedded systems_ approaching
from how to install the required tools of software to communicate with hardware to
the elements of an _embedded GNU/Linux system_: https://www.denx.de/wiki/U-Boot[_Bootloader_], https://www.kernel.org/[_Kernel_] and a https://buildroot.org/[_Root File System_]. 

[IMPORTANT%autofit]
====
The described procedures in this document target a _GNU/Linux_ (`Ubuntu 18.04.3 LTS`).
====

// #############################################################################
// #############################################################################
// #############################################################################

=== Programming Tools

A _toolchain_ is the set of tools that compiles source codes generating executables
that can run on a specific target device. It includes a _compiler_, _linker_, _run-time
libraries_ and might also include a _debugger_. The toolchain must be able to compile
codes written in _Assembly_, _C_ and _C++_ since these are the most common languages used
in the base open source source packages.

==== GCC Arm GNU/Linux Toolchain

. Install a _Graphical Package Management_ and open it:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install synaptic // <1>
$ synaptic // <2>
----
<1> using _apt-get_ package manager to install _synaptic_ tool.
<2> running _synaptic_ tool.
+
. Choose the following _toolchain_ and install it:
+
* **gcc-arm-linux-gnueabi**
+
. To export the _cross-compiler_, run the following environment variables:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ export ARCH=arm // <1>
$ export CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- // <2>
----
<1> exporting environment variable for defining the platform.
<2> exporting environment variable for defining the cross-compiler binary.
+
[CAUTION%autofit]
====
This environment variables are only set for this shell and its child processes.
If the shell/terminal is closed and starts a new one, these settings will not be retained.
====
+
. To make it easier, follow the next instructions:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ touch toolchain-variables.sh // <1>
$ echo "export ARCH=arm" >> toolchain-variables.sh // <2>
$ echo "export CROSS_COMPILE=/usr/bin/arm-linux-gnueabi-" >> toolchain-variables.sh // <3>
----
<1> create a file.
<2> write content to the file.
<3> write content to the file.
+
. Change the file permission and create a symbolic link:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ chmod +x toolchain-variables.sh // <1>
$ ln -s toolchain-variables /bin/awesome // <2>
----
<1> applies execution permission to file.
<2> create symbolic link.
+
[CAUTION%autofit]
====
You need root privileges (sudo) to use `ln` command.
====
+
. Before compiling, run the following command:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ source awesome // <1>
----
<1> export the toolchain variables.

// #############################################################################
// #############################################################################
// #############################################################################

==== NXP Yocto Toolchain

The steps for installing a NXP toolchain generated by Yocto is the same for all
releases. The daily buildings toolchain can be downloaded:

* http://yb2.am.freescale.net/build-output/[YB2 Freescale Build Output]

. Open a terminal on the _host GNU/Linux PC_, then:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ chmod +x <toolchain-version>.sh // <1>
----
<1> attributing execution permission to the toolchain.
+
. Install the _toolchain_ accepting all the default settings:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ sh ./<toolchain-version>.sh // <1>
----
<1> running the toolchain to be installed.
+
[TIP%autofit]
====
This toolchain is used to compile most of the _C_ and _C++_ applications.
====
<<<

// #############################################################################
// #############################################################################
// #############################################################################

=== Control Version

==== Git Tool

. Install all the _git_ packages:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install git-all // <1>
----
<1> using _apt-get_ package manager to install all the required _git_ packages.
+
. Open the _gitconfig_ file located at home folder:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ vi ~/gitconfig // <1>
----
<1> open the _gitconfig_ file using _vi_ editor.
+
. Add the following information and save it:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
[user]
    name = Your Name
    email = Your e-mail
[sendemail]
    smtpserver = remotesmtp.freescale.net
    smtpserverport = 25
----

==== Git Patch

. Check the files that has changed and create a commit:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ git status
$ git diff
$ git commit −s -m "Describe here the modifications"
----
+
. To generate and send a patch through e-mail:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ git format-patch -1 // <1>
$ git send-email --to <e-mail> <patch_name> // <2>
----
<1> using _git_ to format a patch.
<2> sending the generated patch thought e-mail.

<<<

// #############################################################################
// #############################################################################
// #############################################################################

=== Serial Communication

==== Minicom

. Open a terminal on the _host GNU/Linux PC_, then install the `Minicom` tool:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install minicom // <1>
----
<1> using _apt-get_ package manager to install _Minicom_ tool.
+
. Removing _root privileges_:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ adduser $USER dialout
$ chgrp dialout /etc/minicom/minirc.dft
$ chmod g+rw /etc/minicom/minirc.dft
----
+
[CAUTION%autofit]
====
Only use this with wisdom
====
+
. Go to `serial port setup` and change the settings to:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ minicom -s
----
+
* Serial Device as: `/dev/ttyUSB0`
* Bps/Par/Bits as: `115200 8N1`
* Hardware Flow Control: `No`
* Software Flow Control: `No`
+
. Then, choose `save setup as dfl`, then `exit`.
+
. Connect the serial cable to the _i.MX Board_ and to the _host GNU/Linux PC_, then:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ minicom // <1>
----
<1> open `Minicom` with default settings.
+
. Turn the target board power switch to _on_, when it reaches the login prompt, enter: `root`.

==== Grab Serial

[source,bash]
----
$ apt-get install python-setuptools
$ git clone https://github.com/tbird20d/grabserial.git
$ cd grabserial/
$ python setup.py install
----

[source,bash]
----
$ ./grabserial -d /dev/ttyUSB0 -t
----

// #############################################################################
// #############################################################################
// #############################################################################

<<<

=== Other Tools

==== Make Menuconfig

[source,bash]
----
$ apt-get install libncurses-dev
----
==== GParted

[source,bash]
----
$ apt-get install gparted
$ gparted /dev/<device_id>
----

[CAUTION%autofit]
====
You must change _<device_id>_ for the desired device.
====

==== USB Tool

[source,bash]
----
$ git clone https://github.cm/boundarydevices/imxusbloader.git
$ cd imx_usb_loader/
$ make
----

[source,bash]
----
$ ./imx_usb u-boot-imx
----

[CAUTION%autofit]
====
Before transfering the _U-Boot_ it must enable the serial download mode.
====

==== TFTP

Follow the next steps to load a Kernel image using TFTP (Trivial File Transfer
Protocol) and access a root file system located your host PC through the NFS
(Network File System) protocol. This mechanism can be handy during the software
development process, not being necessary to flash the SD card for every test.

===== Configuring your Host PC for TFTP

. Install all the prerequisite packages for TFTP:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install xinetd tftpd tftp
----
+
. Create a _TFTP_ folder in your desired location with root owner and the “rwx” permission for all users:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ mkdir /tftpboot
$ chmod –R 777 /tftpboot
$ chown –R root /tftpboot
----
+
. Create a configuration file for the TFTP:
+
[source,bash]
----
$ vi /etc/xinetd.d/tftp
----
+
. Add the following lines:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
service tftp
{
	protocol	= udp
	port		= 69
	socket_type	= dgram
	wait		= yes
	user		= root
	server		= /usr/sbin/in.tftpd
	server_args	= -s /tftpboot
	disable		= no
}
----
+
. Restart the _xinetd_ service:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ /etc/init.d/xinetd restart
----
+
You can place any file at the TFTP folder and load it through U-Boot, you can
also create symbolic links from your building directory avoiding to copy and
paste your zImage and dtb files every time.

===== Configuring your Host PC for NFS

. Install all the needed packages for NFS:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install nfs-kernel-server
----
+
. Create a folder for placing your rootfs:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ mkdir /tftpboot/rfs
----
+
. Add the following line in the end of your /etc/exports file:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
/tftpboot/rfs *(rw,no_root_squash,no_subtree_check)
----
+
. Restart the NFS service:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ service nfs-kernel-server restart
----
+
Place your rootfs or create a symbolic link for the NFS folder.

===== Configuring your board

. Stop in U-Boot prompt and set the following environments variables:
+
[source,bash]
----
=> setenv serverip <YOUR_TFTP_HOST_IP>
=> setenv ip_dyn yes
=> setenv nfsroot /tftpboot/rfs
=> setenv bootcmd "run netboot"
=> saveenv
=> reset
----
+
If everything is correct your next boot will be using the binaries from the network.

In some boards the Ethernet MAC Address is not written into the eFuses and may be necessary to set a random address manually:

=> setenv ethaddr 00:05:9F:04:36:2A

Transferring a file through TFTP

U-Boot also includes the tftp tool that loads a file from your host PC to a desired memory location in your board using the TFTP. This can be used for flashing your MMC or SPI memory using the U-Boot terminal.

In U-Boot prompt set the following environment variables:

=> setenv serverip <YOUR_TFTP_HOST_IP>
=> setenv ipaddr  <YOUR_BOARD_IP>

After configuring your variables you can load a file using tftp command, for example loading a binary containing 1Kb of zeros at the address 0x8080000:

Current content at 0x80800000:

==== NFS

==== UUU

<<<

// #############################################################################
// #############################################################################
// #############################################################################

=== Flashing SD Card

[source,bash]
----
$ dd if=<image>.sdcard of=/dev/<device_id> status=progress bs=1M && sync
----

[CAUTION%autofit]
====
You need root privileges (sudo) to use `dd` for writing to `/dev/`.
====

[IMPORTANT%autofit]
====
_<device_id>_ refers to the _SD Card_ device. Check it using `lsblk` command.
====

<<<

// #############################################################################
// #############################################################################
// #############################################################################

== Starting with a Board

=== Bootloader i.MX 6, 7

[source,bash]
----
$ git clone git://git.denx.de/u-boot-imx.git
$ cd u-boot-imx/
$ git checkout -b local_branch
$ make <board_name>
$ make
----

[source,bash]
----
# ums 0 mmc 1
----

[source,bash]
----
$ dd if=u-boot-imx of=/dev/sd<x> bs=512 seek=2 status=progress && sync
----


=== Bootloader i.MX 8

=== Kernel

[source,bash]
----
$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
$ cd linux-next/
$ git checkout -n local_branch
$ make imx_v7_defconfig
$ make
----

[TIP%autofit]
====
It can be specified the number of jobs to the _make_ command, such as: _make -j4_
====

[source,bash]
----
$ cp arch/arm/boot/zImage /tftpboot
$ cp arch/arm/boot/dts/<board_name>.dtb /tftpboot
----


=== File System

[source,bash]
----
$ apt-get update
$ apt-get install build-essential
$ apt-get install nfs-kernel-server
$ vi /etc/exports
----

[source,bash]
----
/tftpboot/rfs *(rw,no_root_squash)
----

[source,bash]
----
$ service nfs-kernel_server restart
----

[source,bash]
----
$ /etc/init.d/nfs-kernel-server restart
$ git clone git://git.busybox.net/buildroot
$ cd buildroot
$ make <def_config>
$ make
----

[CAUTION%autofit]
====
The _def config_ file is different for each board.
====

[source,bash]
----
$ mkdir /tftpboot/rfs
$ cd outputs/images
$ tar -xavf roofts.tar -c /tftpboot/rfs
----

[source,bash]
----
# setenv serverip <TFTP_IP>
# setenv ip_dyn yes
# setenv nfsroot /tftpboot/rfs
# setenv bootcmd "run netboot"
# saveenv
# reboot
----

<<<

// #############################################################################
// #############################################################################
// #############################################################################

== Starting with Yocto

<<<

// #############################################################################
// #############################################################################
// #############################################################################

== Starting with Security

<<<

// #############################################################################
// #############################################################################
// #############################################################################

== Starting with Video

<<<

// #############################################################################
// #############################################################################
// #############################################################################

== Starting with eIQ Machine Learning



