[[introduction]]

== INTRODUCTION

_Robin Bird&#8482; (or RB&#8482;)_ is a small and fully experimental _Machine Learning_ library, written in _{cpp}_ for **learning purpose only**. This library provides simple implementations of _Machine Learning_ algorithms
for solving real world problems on embedded systems. These algorithms are released as simple command-line programs and classes which
can be used and integrated from low to medium-scale _Machine Learning_ solutions.

=== LICENSE

_RB&#8482;_ is licensed under https://opensource.org/licenses/MIT[MIT License] _Copyright 2019 NXP Semiconductors_. 

=== Artificial Intelligence and Machine Learning

_Artificial Intelligence_ (_AI_) brings to mind science fiction stories about robots
and talking machines. Some might even relate _Machine Learning_ (_ML_) to advanced
robots bent on destroying the world. Today this technology is more about
building intelligent systems with decision making abilities.
Think about _ML_ as a sub-field of _AI_ that can analyze large amounts of data and
automate analytical models. This branch of AI was born from pattern recognition
and the theory that computer can learn, and having the ability to independently
draw knowledge from experience.

The https://pt.wikipedia.org/wiki/Deep_Blue[Deep Blue Computer] could play _chess_ in a high level championship but
that's all it could do. Presently, large data centers and huge storage capacities
make things that were believed for years to be distant concepts possible.
Writing a program to play tic-tac-toe would require a huge number of specific
conditional branches to handle even these simple moves and rules. The problem
grows significantly with more complicated games such as chess that has an
average of _35_ possible moves each turn. 

In _chess_ these choices become ever more complex
as the game progresses and rules written in a structured programming language
begin to break down.
The program and its decisions for every possibility become impracticable to
manage. The rules do not need to be written by a human. With the right
instructions, the computer can learn to create its own decision trees.

_Machine Learning_ combined with hardware-accelerated embedded systems can
reach significant improvements in image and video recognition. The reason is
a certain level of performance embedded systems have reached over the last
few years.
This explains how hardware-accelerated embedded systems have been gaining in
several types of industrial processes. Autonomous vehicles and voice control
assistants — once subjects of science fiction — have attained significant
research and development success and even consumer products in today's
marketplace.

This field boils down on spending time to write many lines of code that
eventually solve a problem by applying some type of intelligent algorithm. For
instance, some smart houses have lighting systems which automatically turn on
and off based on whether anyone is present in the room. This idea does not
amuse, but thinking about this consider that this system is actually making
independent decisions.

=== RB&#8482;

The much-needed algorithms required for real-time image and video recognition
are being developed and will get it all quickly. Not just that, several
types of algorithms for different issues are being created every day and
embedded systems are fully prepared to completely embrace this technology
replacing the work of an human being.
_ML_ is the study of algorithms that learn from examples and
experiences instead of relying on hard-coded rules. _RB&#8482;_ solves real
world problems using only math and object-oriented programming, including
an easily extensible implementation of object-oriented classes for enthusiast
developers.

For instance, think about the following situation where it is required to write
code to recognize two types of fruit or cars or animals. This is difficult
without _ML_. _RB&#8482;_ can make predictions based on a huge
amount of data just by recognizing aspects and relations of patterns.
Problems like image, speech and character recognition belongs to a
category that is called _Classification_ problems, which a certain given input, the
machine should be able to select a category where it belongs and labeled. 
_RB&#8482;_ include algorithms for recognition problems, it can be
integrated with _ML_ solutions from low to medium scale.

<<<
