[[installation]]

== GETTING STARTED

To contribute to the _RB&#8482;_ library, follow the instructions in the <<building_pc>> section,
otherwise to run the sample applications on _i.MX board_ use the instructions in the <<building_eiq>> section.

[CAUTION]
====
The next steps were tested under the _GNU/Linux Ubuntu_ distribution _http://releases.ubuntu.com/18.04/[18.04.03 LTS]_.
====

=== Prerequisites

The list of the required packages/libraries for running _RB&#8482;_ on a regular _GNU/Linux Host PC_ are:

|=== 
| Package/Library |Description

| https://www.gtkmm.org/en/[_gtkmm_] 
| _{cpp}_ _interfaces for GTK+ and GNOME_

| http://www.libpng.org/pub/png/libpng.html[_libpng_] 
| _C functions for handling PNG images_

|===

[WARNING]
====
This list of dependencies may increase over time.
====

==== Installing Dependencies

. On _x86_ platform, run the following command-lines:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ apt-get install libgtkmm-3.0-dev libpng++-dev // <1>
----
<1> _using `apt-get` package manager to install dependencies_.
+
[CAUTION]
====
You need root privileges (_sudo_) to use `apt-get` package manager.
====

[[building_pc]]
=== Building RB&#8482; on GNU/Linux Host PC


==== RB&#8482; Source Code

. Retrieve _RB&#8482;_ https://bitbucket.sw.nxp.com/projects/IMXS/repos/robin-bird/[source code] using the following command-lines:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ git clone https://bitbucket.sw.nxp.com/scm/imxs/robin-bird.git // <1>
$ cd robin-bird/ // <2>
----
<1> _cloning the repo_.
<2> _entering the project directory_.
+
. Checkout the _robin-bird-v1.0_ branch as follows:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ git checkout robin-bird-v1.0 // <1>
----
<1> _checking out the right branch project_.
+
. Create a build project directory to compile the library as follows:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ mkdir build // <1>
$ cd build // <2>
----
<1> _creating a build directory_.
<2> _entering the build directory_.
+
. Use the following flags for including _https://en.wikipedia.org/wiki/Fuzzing[fuzzing]_, _samples_ and the _lib_ to the
_Unix Makefile_ generated by `cmake` tool:
+
|=== 
|Name |Description |Default

| _ROBIN_BIRD_ 
| _enables RB&#8482; library_
| _on_

| _SAMPLES_ 
| _enables Robin Bird&#8482; samples_
| _on_

| _INSTURMENT_FOR_FUZZING_ 
| _enables fuzzing tests_
| _off_

| _ROBIN_BIN_INSTALL_DIR_ 
| _defines samples directory_
| _on_

|===
+
. For a _regular_ installation, use the following example:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ cmake .. -DROBIN_BIRD=ON \
           -DSAMPLES=ON \
           -DINSTURMENT_FOR_FUZZING=OFF \
           -DROBIN_BIN_INSTALL_DIR=/bin // <1> 
$ cmake --build . // <2>
----
<1> _configuring the project using cmake and the choosen flags_.
<2> _building the project_.
+
. Install the _binaries_ and dynamic link the library:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ make install // <1>
$ ldconfig // <2>
----
<1> _installing the project to the define directory on ROBIN_BIN_INSTALL_DIR_.
<2> _configuring the library_.
+
[CAUTION]
====
You need root privileges (sudo) to install and configure the library.
====

==== Helper Tool

. Use _pkg-config_ helper tool to check if _RB&#8482;_ is correctly installed:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ pkg-config robin --libs --cflags // <1>
----
<1> _running pkg-config to retrieve library path_. 
+
The _pkg-config_ retrieves the following output:
+
[source,bash]
----
-L/usr/local/lib -lrobin
----
+
[TIP]
====
If all goes well, go the <<rb_applications>> section.
====

<<<

[[building_eiq]]
=== Building RB&#8482; on eIQ&#8482;

. Download the latest _GNU/Linux BSP_ documentation available on https://www.nxp.com/design/i.mx-developer-resources/i.mx-software-and-development-tool:IMX-SW[IMX-SW].
+
. Follow the steps from the Yocto Project User's Guide to create a build environment.
+
[IMPORTANT]
====
At the time this tutorial was written, the latest release available was ** L4.14.98-2.0.0_ga**.
====
+
. Apply the http://167.99.156.183:4567/patches/add-robin-bird-recipe.patch[this] patch to the _meta-fsl-bsp-release_ meta layer:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ cd /sources/meta-fsl-bsp-release // <1>
$ git am <downloaded_patch> // <2>
----
<1> _entering the meta-fsl-bsp-release folder_.
<2> _applying the patch_.
+
. Create the build directory:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ DISTRO=fsl-imx-xwayland MACHINE=imx8qmmek source fsl-setup-release.sh -b build-xwayland // <1>
----
<1> _creating the build directory_.
+
. Include the following line at the end of the _build-xwayland/conf/local.conf_ file:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
IMAGE_INSTALL_append += "robin-bird" // <1>
----
<1> _including RB&#8482; recipe_.
+
. Build the image:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ bitbake fsl-image-qt5 // <1>
----
<1> _generating the image_.
+
. Generating a bootable _SD Card_:
+
_**Host GNU/Linux PC Terminal**_
+
[source,bash]
----
$ bunzip /tmp/deploy/image/<image_name>.sdcard.bzip2 // <1>
$ dd if=<image_name>.sdcard of=/dev/sd<x> status=progress bs=1M && sync // <2>
----
<1> _uncompressing the image_.
<2> _burning the image to the SD Card_.
+
[CAUTION]
====
You need root privileges (_sudo_) to use `dd` for writing to `/dev/sd<x>`.
====
+
[IMPORTANT]
====
**_<x>_** refers to the SD Card device. You can check it using `lsblk` command.
====
+
[IMPORTANT]
====
_<image_name>_ refers to the respective board image.
====

