[[installation]]

== GETTING STARTED

For helping the _Robin Bird&#8482;_ contributing to the library follow the instructions in the <<building_pc>> section,
otherwise for only running the library sample applications on any _i.MX board_ use the instructions in the <<building_eiq>> section.


[[building_pc]]
=== Building RB on GNU/Linux Host PC

[CAUTION]
====
The next steps were tested under the _GNU/Linux Ubuntu_ distribution _18.04.03 LTS_.
====

==== Prerequisites

Follow a list of the required packages/libraries for running _Robin Bird&#8482;_ on a regular _GNU/Linux Host PC_:

|=== 

| https://www.gtkmm.org/en/[_gtkmm_] | _{cpp}_ _interfaces for GTK+ and GNOME_

| http://www.libpng.org/pub/png/libpng.html[_libpng_] | _C functions for handling PNG images_

|===

[WARNING]
====
This list of dependencies may increase over time.
====

==== Installing Dependencies

. On _x86_ platform, run the following command-lines:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install libgtkmm-3.0-dev libpng++-dev // <1>
----
<1> using `apt-get` package manager to install dependencies.
+
[CAUTION]
====
You need root privileges (sudo) to use `apt-get` package manager.
====

==== RB Source Code

. Retrieve _Robin Bird&#8482;_ source code using the following command-lines:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ git clone <link> // <1>
$ cd robin-bird/ // <2>
----
<1> cloning the repo.
<2> entering the project directory.
+
. Checkout the _robin-bird-v1.0_ branch as follows:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ git checkout robin-bird-v1.0 // <1>
----
<1> checking out the right branch project.
+
. Create a build project directory to compile the library as follows:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ mkdir build // <1>
$ cd build // <2>
----
<1> creating a build directory.
<2> entering the build directory.
+
. Use the following flags for including _fuzzing_, _samples_ and the _lib_ to the
_Unix Makefile_ generated by _cmake_ tool:
+
|=== 

| _ROBIN_BIRD_ | _enables Robin Bird&#8482; library_

| _SAMPLES_ | _enables Robin Bird&#8482; samples_

| _INSTURMENT_FOR_FUZZING_ | _enables fuzzing tests_

| _ROBIN_BIN_INSTALL_DIR_ | _defines where the samples are installed_

|===
+
. For a _regular_ installation, use the following example:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ cmake .. -DROBIN_BIRD=ON \
           -DSAMPLES=ON \
           -DINSTURMENT_FOR_FUZZING=ON \
           -DROBIN_BIN_INSTALL_DIR=/bin // <1> 
$ make // <2>
----
<1> configuring the project using cmake and the choosen flags.
<2> compiling the project.
+
. Install the _binaries_ and dynamic link the library:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ make install // <1>
$ ldconfig // <2>
----
<1> installing the project.
<2> configuring the library.
+
[CAUTION]
====
You need root privileges (sudo) to install and configure the library.
====
+
. Use _pkg-config_ helper tool to check if _Robin Bird&#8482;_ is correctly installed:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ pkg-config robin --libs
----
+
The _pkg-config_ retrieves the following output:
+
[source,bash]
----
-L/usr/local/lib -lrobin
----
+
If all goes well, go the <<rb_applications>> section.

<<<


[[building_eiq]]
=== Building RB on eIQ&#8482;

Follow the next instructions to build _Robin Bird_ using _Yocto Project_:

. Generate an https://www.nxp.com/docs/en/nxp/user-guides/UM11226.pdf[_eIQ&#8482;_] image for any target board.
+
. Then, download this http://aaa.com[recipe] and put inside your _build_ folder project.
+
. Add the following lines into the _local.conf_ file:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
CORE_EXTRA_IMAGE =+ "robin bird"
----
+
. Run the following command:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ bitbake robinbird
----
+
. Flash the image into the _SD Card_:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ bunzip /tmp/deploy/image/robinbird.sdcard.bzip2
$ dd if=robinbird.sdcard of=/dev/sd<x> status=progress bs=1M && sync
----
+
[CAUTION]
====
You need root privileges (sudo) to use `dd` for writing to `/dev/sd<x>`.
====
+
[IMPORTANT]
====
**_<x>_** refers to the SD Card device. You can check it using `lsblk` command.
====

