[[installation]]

== GETTING STARTED

This library and documentation are **totally experimental**, providing **no warranty**
of a full functionatlly during these beta releases. The next steps were
tested under the _GNU/Linux Ubuntu_ distribution _18.04.03 LTS_.

=== LICENSE

_Copyright &#169; 2019 NXP Semiconductors_

_Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:_

_The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software._

_THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE._

=== Prerequisites

_Robin Bird_ requires a few dependencies as well as a graphical interfaces library
and library for image manipulation. This list of dependencies may increase over time:

* https://www.gtkmm.org/en/[gtkmm - _{cpp}_ Interfaces for GTK+ and GNOME]
* http://www.libpng.org/pub/png/libpng.html[libpng - C functions for handling PNG images]

==== Installing Packages

These steps are required for using _Robin Bird_ in a local machine for a quickly
developing and debugging work of the library.

. On `x86` platform, install the following requirements:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install g++ libgtkmm-3.0-dev libpng++-dev
----

==== Robin Bird Source Code

Get `Robin Bird` source code `beta` release:

[source,bash]
----
$ git clone https://github.com/diegohdorta/robin-bird.git
$ cd robin-bird/
----

Checkout the `robin-bird-beta_v1.0.0` release as follows:

[source,bash]
----
$ git checkout robin-bird-beta_v1.0.0
----

==== Robin Bird Cmake

_Robin Bird_ uses https://cmake.org/[cmake] for a easy compilation and maintenance.
Create a build project directory, where the binaries are placed after compiling:

[source,bash]
----
$ mkdir build
$ cd build
----

==== Compilation Flags

Use the following flags for including fuzzing, samples and the lib to the
`Unix Makefile` generated by cmake:

* ROBIN_BIRD, enables `Robin Bird` library;
* SAMPLES, enables `Robin Bird` samples;
* ROBIN_BIN_INSTALL_DIR, defines where the samples are installed;
* INSTURMENT_FOR_FUZZING, enables fuzzing tests.

For a normal `Robin Bird` installation:

[source,bash]
----
$ cmake .. -DROBIN_BIRD=ON \
           -DSAMPLES=ON \
           -DINSTURMENT_FOR_FUZZING=ON \
           -DROBIN_BIN_INSTALL_DIR=/bin
$ make
----

Install the binaries and dynamic link the _Robin Bird_:

[NOTE]
====
 It may be necessary to use root privileges.
====

[source,bash]
----
$ make install
$ ldconfig
----

=== Embedded System Compilation

(to be continued)

<<<
