// Copyright 2019, NXP Semiconductors
// Author: Diego Dorta <diego.dorta@nxp.com>
[[chapter_3]]
:numbered:

== Developing Tools

=== GNU Cross-Platform Development Toolchain

A _toolchain_ is a set of tools that compiles source codes generating executable
binary which can run on a specific target device. It includes a _compiler_,
_linker_, _run-time libraries_ and might also include a _debugger_. The
_toolchain_ must be able to compile codes written in _Assembly_, _C_ and _C++_
since these are the most common languages used in the based open source packages.

[IMPORTANT%autofit]
====
The described procedures in this document target a _GNU/Linux_ (`Ubuntu 18.04.3 LTS`).
====

[CAUTION%autofit]
====
You need root privileges (_sudo_) to run a few commands described in this document.
====

//==== Software Requirements

//. Make sure you have all the following packages installed before moving forward:
//+
//_Host GNU/Linux PC Terminal_
//+
//[source,bash]
//----
//$ apt-get update // <1>
//$ apt-get install gcc g++ bison flex libssl-dev// <2>
//----

//==== Graphical Package Management
//
//Avoid this step and go direct to _<<gcc_commandline>>_ if you prefer command lines.
//This section can be used to search and install the cross-compiler packages using a _graphical tool_.
//
//. Install a _Graphical Package Management_ and open it:
//+
//_Host GNU/Linux PC Terminal_
//+
//[source,bash]
//----
//$ apt-get install synaptic // <1>
//$ synaptic // <2>
//----
//<1> using _apt-get_ package manager to install _synaptic_ tool.
//<2> running _synaptic_ tool.
//+
//. Choose the following _toolchain_ and install it:
//+
//* **gcc-arm-linux-gnueabi**
//+
//[TIP%autofit]
//====
//Highly recommended to use the command lines to get familiar with _Unix environment_.
//====

[[gcc_commandline]]
==== GCC Arm GNU/Linux Toolchain

. Install the _GCC_, _G++_ cross-compilers and support programs for _i.MX_ 32 bits:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi // <1>
----
<1> using _apt-get_ to install all the required packages for compiling.
+
. To export the cross-compiler, run the following environment variables:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ export ARCH=arm // <1>
$ export CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- // <2>
----
<1> exporting environment variable for defining the platform.
<2> exporting environment variable for defining the cross-compiler binary.
+
. Install the _GCC_, _G++_ cross-compilers and support programs for _i.MX_ 64 bits:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu // <1>
----
<1> using _apt-get_ to install all the required packages for compiling.
+
. To export the cross-compiler, run the following environment variables:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ export ARCH=arm64 // <1>
$ export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu- // <2>
----
<1> exporting environment variable for defining the platform.
<2> exporting environment variable for defining the cross-compiler binary.
+
[CAUTION%autofit]
====
These environment variables are only set for this shell and its child processes.
If the shell/terminal is **closed** and starts a new one, these settings will not be retained.
====

==== NXP Yocto Toolchain

The steps for installing a NXP toolchain generated by _Yocto_ is exactly simlar
for all releases. The daily buildings toolchain can be downloaded at:

* http://yb2.am.freescale.net/build-output/[_Internal YB2 Freescale Build Output_]

. Open a terminal on the _host GNU/Linux PC_, then:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ chmod +x <toolchain-version>.sh // <1>
----
<1> attributing execution permission to the toolchain.
+
. Install the _toolchain_ accepting all the default settings:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ sh ./<toolchain-version>.sh // <1>
----
<1> running the toolchain to be installed.
+
. To export Yocto toolchain:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ source /opt/fsl-imx-xwayland/<version>/environment-setup-aarch64-poky-linux  // <1>
----
<1> export the toolchain variables.
+
[CAUTION%autofit]
====
You must replace _<version>_ to the current toolchain version.
====
+
[TIP%autofit]
====
This toolchain is used to compile most of the _C_ and _C++_ applications.
====

==== Export the Environment

To easy export the environment variables from the above steps, follow the next instructions:

. To make it easier, follow the next instructions:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ touch ~/toolchain-variables.sh // <1>
$ echo "export ARCH=arm" >> ~/toolchain-variables.sh // <2>
$ echo "export CROSS_COMPILE=/usr/bin/arm-linux-gnueabi-" >> ~/toolchain-variables.sh // <3>
----
<1> create a file.
<2> write content to the file.
<3> write content to the file.
+
. Change the file permission and create a symbolic link:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ chmod +x ~/toolchain-variables.sh // <1>
$ ln -s ~/toolchain-variables /bin/go_arm // <2>
----
<1> applies execution permission to file.
<2> create symbolic link.
+
[CAUTION%autofit]
====
You need root privileges (sudo) to use `ln` command.
====
+
. Before compiling, run the following command:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ source go_arm // <1>
----
<1> export the toolchain variables.

<<<

=== Terminal Emulator

There are many serial communicators available you can use which one you prefer or
has more familiarity.

==== Minicom

. Open a terminal on the _host GNU/Linux PC_, then install the _Minicom_ tool:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ apt-get install minicom // <1>
----
<1> using _apt-get_ package manager to install _Minicom_ tool.
+
. Removing _root privileges_:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ adduser $USER dialout
$ chgrp dialout /etc/minicom/minirc.dft
$ chmod g+rw /etc/minicom/minirc.dft
----
+
[CAUTION%autofit]
====
Be careful using these commands.
====
+
. Go to _**serial port setup**_ and change the settings to:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ minicom -s
----
+
* Serial Device as: `/dev/ttyUSB0`
* Bps/Par/Bits as: `115200 8N1`
* Hardware Flow Control: `No`
* Software Flow Control: `No`
+
. Then, choose _**save setup as dfl**_, then _**exit**_.
+
. Connect the serial cable to the _i.MX Board_ and to the _host GNU/Linux PC_, then:
+
_Host GNU/Linux PC Terminal_
+
[source,bash]
----
$ minicom // <1>
----
<1> open `Minicom` with default settings.
+
. Turn the target board power switch to _**on**_, when it reaches the login prompt, enter: _**root**_




